version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/_site_demo_rails
    environment:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    steps:
      - checkout
      - run:
          name: Install rsync
          command: sudo apt install rsync
      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run:
          name: Install dependencies
          command: bundle install
      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Deploy
          command: rsync -e "ssh -o StrictHostKeyChecking=no" -va --delete ./demo_rails lassuncao@167.99.226.237:~/deployments/demo-rails
